;; This file is automatically generated by the multiple-cursors
;; extension.
;; It keeps track of your preferences for running commands with
;; multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        evil-forward-char
        evil-previous-line
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        evil-mouse-drag-region
        evil-next-line
        ))
